[build]
  functions = "netlify/functions"
  publish = "." # Use "." if there is no specific directory to publish
  command = "npm run build" # Adjust this if you have a different build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  [functions.maxDuration]
  seconds = 10
  node_bundler = "esbuild"

[context.production.environment]
  DATABASE_URL = "your-database-url"

[context.development.environment]
  DATABASE_URL = "your-development-database-url"
